tasks:
  - name: Installing Ionic 5 & Cordova
    command: npm install -g @ionic/cli cordova && cd mobdev-ca2 && npm i -g cordova && ionic cordova plugin add cordova-sqlite-storage && npm install @ionic/storage
